name: qbridge
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pandas=2.3.1
  - scipy=1.13.1
  - matplotlib=3.9.4
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - torch-geometric==2.6.1
      - qiskit==0.44.2
      - qiskit-terra==0.25.2.1
      - qiskit-aer==0.12.2
      - qiskit-ibm-provider==0.7.0
      - qiskit-optimization==0.5.0
      - qiskit-qasm3-import==0.2.0
      - scikit-learn==1.6.1
      - exrex==0.12.0
      - ktrain==0.41.4
      - git+https://github.com/qiskit-community/qiskit-textbook.git#subdirectory=qiskit-textbook-src